const users = [
  {
    firstname: "John",
    lastname: "Doe",
    email: "johndoe@example.com",
    phone: "1234567890",
    education: "Bachelor's Degree",
    dob: ["1990-01-01"],
    username: "johndoe",
    password: "password123",
    confirmPassword: "password123",
    isActive: false,
    houseno: "123",
    street: "Main Street",
    ward: "Ward 1",
    township: "Township A",
    town: "City X",
  },
  {
    firstname: "Jane",
    lastname: "Smith",
    email: "janesmith@example.com",
    phone: "9876543210",
    education: "Master's Degree",
    dob: ["1985-05-15"],
    username: "janesmith",
    password: "securepassword",
    confirmPassword: "securepassword",
    isActive: true,
    houseno: "456",
    street: "Oak Avenue",
    ward: "Ward 2",
    township: "Township B",
    town: "City Y",
  },
  {
    firstname: "Alice",
    lastname: "Johnson",
    email: "alicejohnson@example.com",
    phone: "1112223333",
    education: "High School Diploma",
    dob: ["1995-08-20"],
    username: "alicej",
    password: "test1234",
    confirmPassword: "test1234",
    isActive: true,
    houseno: "789",
    street: "Maple Street",
    ward: "Ward 3",
    township: "Township C",
    town: "City Z",
  },
  {
    firstname: "Bob",
    lastname: "Smithson",
    email: "bobsmithson@example.com",
    phone: "4445556666",
    education: "Associate's Degree",
    dob: ["1998-03-10"],
    username: "bobsmith",
    password: "pass1234",
    confirmPassword: "pass1234",
    isActive: true,
    houseno: "321",
    street: "Cedar Avenue",
    ward: "Ward 4",
    township: "Township D",
    town: "City W",
  },
  {
    firstname: "Emily",
    lastname: "Davis",
    email: "emilydavis@example.com",
    phone: "7778889999",
    education: "Doctorate Degree",
    dob: ["1980-12-05"],
    username: "emilyd",
    password: "abc123",
    confirmPassword: "abc123",
    isActive: false,
    houseno: "555",
    street: "Elm Street",
    ward: "Ward 5",
    township: "Township E",
    town: "City V",
  },
  {
    firstname: "Michael",
    lastname: "Brown",
    email: "michaelbrown@example.com",
    phone: "3334445555",
    education: "Bachelor's Degree",
    dob: ["1992-07-15"],
    username: "michaelb",
    password: "pass456",
    confirmPassword: "pass456",
    isActive: true,
    houseno: "888",
    street: "Pine Avenue",
    ward: "Ward 6",
    township: "Township F",
    town: "City U",
  },
  {
    firstname: "Sophia",
    lastname: "Martinez",
    email: "sophiamartinez@example.com",
    phone: "6667778888",
    education: "Master's Degree",
    dob: ["1989-04-25"],
    username: "sophiam",
    password: "testpass",
    confirmPassword: "testpass",
    isActive: true,
    houseno: "999",
    street: "Willow Lane",
    ward: "Ward 7",
    township: "Township G",
    town: "City T",
  },
  {
    firstname: "David",
    lastname: "Wilson",
    email: "davidwilson@example.com",
    phone: "5556667777",
    education: "High School Diploma",
    dob: ["1997-09-30"],
    username: "davidw",
    password: "password1",
    confirmPassword: "password1",
    isActive: false,
    houseno: "666",
    street: "Sycamore Street",
    ward: "Ward 8",
    township: "Township H",
    town: "City S",
  },
  {
    firstname: "Olivia",
    lastname: "Anderson",
    email: "oliviaanderson@example.com",
    phone: "9990001111",
    education: "Associate's Degree",
    dob: ["1994-02-18"],
    username: "oliviaa",
    password: "passpass",
    confirmPassword: "passpass",
    isActive: true,
    houseno: "111",
    street: "Chestnut Avenue",
    ward: "Ward 9",
    township: "Township I",
    town: "City R",
  },
  {
    firstname: "Daniel",
    lastname: "Thomas",
    email: "danielthomas@example.com",
    phone: "2223334444",
    education: "Bachelor's Degree",
    dob: ["1993-11-22"],
    username: "danield",
    password: "testtest",
    confirmPassword: "testtest",
    isActive: false,
    houseno: "222",
    street: "Birch Street",
    ward: "Ward 10",
    township: "Township J",
    town: "City Q",
  },
  {
    firstname: "Ava",
    lastname: "Garcia",
    email: "avagarcia@example.com",
    phone: "8889990000",
    education: "Master's Degree",
    dob: ["1987-06-12"],
    username: "avag",
    password: "password1234",
    confirmPassword: "password1234",
    isActive: true,
    houseno: "777",
    street: "Poplar Lane",
    ward: "Ward 11",
    township: "Township K",
    town: "City P",
  },
  {
    firstname: "Ethan",
    lastname: "Rodriguez",
    email: "ethanrodriguez@example.com",
    phone: "7778889999",
    education: "Doctorate Degree",
    dob: ["1983-03-08"],
    username: "ethanr",
    password: "passpass123",
    confirmPassword: "passpass123",
    isActive: false,
    houseno: "333",
    street: "Walnut Street",
    ward: "Ward 12",
    township: "Township L",
    town: "City O",
  },
  {
    firstname: "Mia",
    lastname: "Lopez",
    email: "mialopez@example.com",
    phone: "5556667777",
    education: "Bachelor's Degree",
    dob: ["1996-10-27"],
    username: "mial",
    password: "abc1234",
    confirmPassword: "abc1234",
    isActive: true,
    houseno: "444",
    street: "Cypress Lane",
    ward: "Ward 13",
    township: "Township M",
    town: "City N",
  },
  {
    firstname: "James",
    lastname: "Perez",
    email: "jamesperez@example.com",
    phone: "3334445555",
    education: "High School Diploma",
    dob: ["1999-04-30"],
    username: "jamesp",
    password: "test12345",
    confirmPassword: "test12345",
    isActive: true,
    houseno: "555",
    street: "Hickory Lane",
    ward: "Ward 14",
    township: "Township N",
    town: "City M",
  },
  {
    firstname: "Charlotte",
    lastname: "Gonzalez",
    email: "charlottegonzalez@example.com",
    phone: "6667778888",
    education: "Associate's Degree",
    dob: ["1991-01-15"],
    username: "charlotteg",
    password: "passpasspass",
    confirmPassword: "passpasspass",
    isActive: true,
    houseno: "999",
    street: "Magnolia Avenue",
    ward: "Ward 15",
    township: "Township O",
    town: "City L",
  },
  {
    firstname: "Benjamin",
    lastname: "Hernandez",
    email: "benjaminhernandez@example.com",
    phone: "9990001111",
    education: "Master's Degree",
    dob: ["1986-07-20"],
    username: "benjaminh",
    password: "abcabc123",
    confirmPassword: "abcabc123",
    isActive: false,
    houseno: "111",
    street: "Palm Lane",
    ward: "Ward 16",
    township: "Township P",
    town: "City K",
  },
  {
    firstname: "Isabella",
    lastname: "Parker",
    email: "isabellaparker@example.com",
    phone: "4445556666",
    education: "Bachelor's Degree",
    dob: ["1990-12-10"],
    username: "isabellap",
    password: "password12345",
    confirmPassword: "password12345",
    isActive: true,
    houseno: "888",
    street: "Rose Lane",
    ward: "Ward 17",
    township: "Township Q",
    town: "City J",
  },
  {
    firstname: "William",
    lastname: "Wright",
    email: "williamwright@example.com",
    phone: "2223334444",
    education: "Doctorate Degree",
    dob: ["1984-08-15"],
    username: "williamw",
    password: "testpass123",
    confirmPassword: "testpass123",
    isActive: false,
    houseno: "777",
    street: "Daisy Lane",
    ward: "Ward 18",
    township: "Township R",
    town: "City I",
  },
  {
    firstname: "Avery",
    lastname: "Morales",
    email: "averymorales@example.com",
    phone: "1112223333",
    education: "High School Diploma",
    dob: ["1998-02-28"],
    username: "averym",
    password: "passwordpass",
    confirmPassword: "passwordpass",
    isActive: true,
    houseno: "666",
    street: "Tulip Lane",
    ward: "Ward 19",
    township: "Township S",
    town: "City H",
  },
  {
    firstname: "Evelyn",
    lastname: "Flores",
    email: "evelynflores@example.com",
    phone: "7778889999",
    education: "Associate's Degree",
    dob: ["1997-11-05"],
    username: "evelynf",
    password: "abc12345",
    confirmPassword: "abc12345",
    isActive: false,
    houseno: "333",
    street: "Violet Lane",
    ward: "Ward 20",
    township: "Township T",
    town: "City G",
  },
];

export default users;
